Description: Create a CodePipeline for a Machine Learning Model
Parameters:
  GitHubToken:
    NoEcho: true
    Description: Secret. It might look something like 9b189a1654643522561f7b3ebd44a1531a4287af OAuthToken with access to Repo. Go to https://github.com/settings/tokens
    Type: String
  GitHubUser:
    Default: brightsparc
    Description: GitHub UserName
    Type: String
  Repo:
    Default: sam-sagemaker
    Description: GitHub Repo to pull from. Only the Name. not the URL
    Type: String
  Branch:
    Default: stepfunctions-workflow
    Description: Branch to use from Repo. Only the Name. not the URL
    Type: String
  DataBucket:
    Default: sagemaker-ap-southeast-2-691313291965
    Type: String
    Description: Name of the model
  BucketPrefix:
    Default: mlops
    Type: String
    Description: Name of the model
  ModelName:
    Default: v1
    Type: String
    Description: Name of the model

Resources:  
  TrainModelProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-job-train
      Description: Trains machine learning model using SageMaker
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            exported-variables:
              - STEPFUNCTION_ARN          
          phases:
            install:
              runtime-versions:
                python: 3.7
              commands:
                - echo "Installing requirements and aws datascience sdk form source"
                - pip install -r workflow/training/requirements.txt
                - pip install git+https://github.com/aws/aws-step-functions-data-science-sdk-python
            pre_build:
              commands:
                - echo "Running data_prep.py"
                - python workflow/training/data_prep.py "${DataBucket}" "${BucketPrefix}"
            build:
              commands:
                - echo "Running training.py"
                - python workflow/training/training.py "${DataBucket}" "${BucketPrefix}" "${SagemakerExecutionRole.Arn}" "${WorkflowExecutionRole.Arn}" "${ModelName}" $CODEBUILD_RESOLVED_SOURCE_VERSION
                - echo "Running suggest_baseline.py"
                - python workflow/training/suggest_baseline.py ${DataBucket}" "${BucketPrefix}" 
            post_build:
              commands:
                - echo "Exporting env vars"
                - source cloud_formation/training.vars
          artifacts:
            files:
              - '**/*'
      TimeoutInMinutes: 30
    
  MLOpsJobMonitor:
    Type: "AWS::Lambda::Function"
    Properties: 
      FunctionName: !Sub ${AWS::StackName}-job-monitor
      Handler: index.lambda_handler
      MemorySize: 512
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      Timeout: 60
      Code: 
        ZipFile: !Sub |
          import boto3
          sagemaker = boto3.client('sagemaker')
          cloudwatch_events = boto3.client('events')
          codepipeline = boto3.client('codepipeline')
          def lambda_handler(event, context):
            pipeline_name = '${AWS::StackName}'
            result = None
            token = None
            try:
              response = codepipeline.get_pipeline_state( name=pipeline_name )
              executionId = response['stageStates'][0]['latestExecution']['pipelineExecutionId']
              
              # Get the approve train status token
              for stageState in response['stageStates']:
                if stageState['stageName'] == 'TrainApproval':
                  for actionState in stageState['actionStates']:
                    if actionState['actionName'] == 'ApproveTrain':
                      latestExecution = actionState['latestExecution']
                      if latestExecution['status'] != 'InProgress':
                        raise(Exception("Train approval is not awaiting for approval: %s" % latestExecution['status']))
                      token = latestExecution['token']
              if token is None:
                raise(Exception("Action token wasn't found. Aborting..."))
                  
              response = sagemaker.describe_training_job( 
                TrainingJobName='mlops-${ModelName}-%s' % executionId )
              
              status = response['TrainingJobStatus']
              print(status)
              
              if status == "Completed":
                result={
                  'summary': 'Model trained successfully',
                  'status': 'Approved'
                }
              elif status == "InProgress":
                return "Training (%s) in progress" % executionId
              else:
                result={
                  'summary': response['FailureReason'],
                  'status': 'Rejected'
                }
            except Exception as e:
              result={
                'summary': str(e),
                'status': 'Rejected'
              }
            
            codepipeline.put_approval_result(
              pipelineName=pipeline_name,
              stageName='TrainApproval',
              actionName='ApproveTrain',
              result=result,
              token=token
            )
            # disable monitoring event
            cloudwatch_events.disable_rule( Name='${AWS::StackName}-job-monitor')
            
            return "Done"
      Description: "Function that will start a new Sagemaker Training Job"
      
  MLOpsJobMonitorPermissions:
    Type: "AWS::Lambda::Permission"
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Sub ${AWS::StackName}-job-monitor
      Principal: events.amazonaws.com
      SourceArn: !GetAtt JobMonitoringEvent.Arn
    DependsOn: MLOpsJobMonitor

  JobMonitoringEvent:
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "Event that will monitor the training job and inform codepipeline as it finishes"
      Name: !Sub ${AWS::StackName}-job-monitor
      ScheduleExpression: cron(0/1 * * * ? *)
      State: DISABLED
      Targets:
        - Arn: !GetAtt MLOpsJobMonitor.Arn
          Id: !Sub mlops-event-${ModelName}
    DependsOn: MLOpsJobMonitor
  
  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub ${AWS::StackName}
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
          Type: S3
          Location: !Sub mlops-${AWS::Region}-${AWS::AccountId}
      Stages:
        -
          Name: Source
          Actions: 
            - 
              Name: SourceAction
              ActionTypeId: 
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts: 
                - Name: ModelSourceOutput
              Configuration: 
                Owner: !Ref 'GitHubUser'
                Repo: !Ref 'Repo'
                Branch: !Ref 'Branch'
                OAuthToken: !Ref 'GitHubToken'
              RunOrder: 1
        -
          Name: Train
          Actions:
            -
              Name: TrainModel
              InputArtifacts:
                - Name: ModelSourceOutput
              OutputArtifacts:
                - Name: ModelTrainOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref TrainModelProject
              RunOrder: 1
        -
          Name: TrainApproval
          Actions:
            -
              Name: ApproveTrain
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              Configuration:
                  CustomData: 'Was this model trained successfully?'
              RunOrder: 1
        -
          Name: DeployDev
          Actions:
            - 
              Name: DeployModelDev
              InputArtifacts:
                - Name: ModelSourceOutput
                - Name: ModelTrainOutput
              OutputArtifacts:
                - Name: ModelDeployDevOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CFNRole.Arn
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub ${AWS::StackName}-deploy-dev
                TemplateConfiguration: ModelTrainOutput::assets/deploy-model.json
                TemplatePath: ModelSourceOutput::assets/deploy-model-dev.yml
              RunOrder: 1
        -
          Name: DeployApproval
          Actions:
            -
              Name: ApproveDeploy
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              Configuration:
                  CustomData: 'Shall this model be put into production?'
              RunOrder: 1
        -
          Name: DeployPrd
          Actions:
            - 
              Name: DeployModelPrd
              InputArtifacts:
                - Name: ModelSourceOutput
                - Name: ModelTrainOutput
              OutputArtifacts:
                - Name: ModelDeployPrdOutput
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
                
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: !GetAtt CFNRole.Arn
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub ${AWS::StackName}-deploy-prd
                TemplateConfiguration: ModelTrainOutput::assets/deploy-model.json
                TemplatePath: ModelSourceOutput::assets/deploy-model-prd.yml
              RunOrder: 1
    # DependsOn:
    #   TrainModelProject

  SagemakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-sagemaker-role 
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [sagemaker.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
                - s3:ListBucket
                Effect: Allow
                Resource: arn:aws:s3:::*

  WorkflowExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-stepfunctions-role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [states.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
      Policies:
        - PolicyName: SageMakerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - sagemaker:*
                - lambda:InvokeFunction
                Resource: "*"
                Effect: Allow
              - Action:
                - iam:PassRole
                Resource: "*"
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com
                Effect: Allow
              - Action:
                - events:PutTargets
                - events:PutRule
                - events:DescribeRule
                Resource:
                - arn:aws:events:*:*:rule/StepFunctionsGetEventsForSageMakerTrainingJobsRule
                - arn:aws:events:*:*:rule/StepFunctionsGetEventsForSageMakerTransformJobsRule
                - arn:aws:events:*:*:rule/StepFunctionsGetEventsForSageMakerTuningJobsRule
                - arn:aws:events:*:*:rule/StepFunctionsGetEventsForECSTaskRule
                - arn:aws:events:*:*:rule/StepFunctionsGetEventsForBatchJobsRule
                Effect: Allow

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-mlops-role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - sagemaker:*
                  - iam:PassRole
                  - s3:*
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DeleteAlarms
                Effect: Allow
                Resource: '*'

  CFNRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-cfn-role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [cloudformation.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CloudFormationRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - sagemaker:*
                  - iam:PassRole
                  - s3:*
                  - application-autoscaling:*
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:DeleteAlarms
                Effect: Allow
                Resource: '*'

  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-pipeline-role
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodePipelineAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - s3:*
                - codebuild:*
                - cloudformation:CreateStack
                - cloudformation:DescribeStacks
                - cloudformation:DeleteStack
                - cloudformation:UpdateStack
                - cloudformation:CreateChangeSet
                - cloudformation:ExecuteChangeSet
                - cloudformation:DeleteChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:SetStackPolicy
                - iam:PassRole
                - sns:Publish
                Effect: Allow
                Resource: '*'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-codebuild-role
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: UploadAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - codepipeline:*
                - sagemaker:*
                - s3:*
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                Effect: Allow
                Resource: '*'
              - Action:
                - iam:PassRole
                Effect: Allow
                Resource: !GetAtt SagemakerExecutionRole.Arn
  
    
